let state=null;
async function api(path,body){const r=await fetch(path,{method:body?"POST":"GET",headers:{"Content-Type":"application/json"},body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw Error(d.error||"Erro");return d}
async function load(){state=await api("/api/state");render()} 
function show(id){document.querySelectorAll(".screen").forEach(x=>x.classList.remove("active"));document.getElementById(id).classList.add("active");document.getElementById("menu").classList.remove("open"); if(id==="wallet"||id==="missions"||id==="ranking"||id==="profile")render()}
function toggleMenu(){document.getElementById("menu").classList.toggle("open")}
function render(){if(!state)return;const p=state.player;
["walletCoins","gameCoins"].forEach(id=>document.getElementById(id).textContent=p.coins);
document.getElementById("profileName").textContent=p.name;document.getElementById("levelText").textContent="Nível "+p.level;document.getElementById("statLevel").textContent=p.level;document.getElementById("statLevels").textContent=p.completedLevels.length;document.getElementById("statAch").textContent=p.achievements?.length||0;
const need=p.level*250;document.getElementById("xpBar").style.width=Math.min(100,p.xp/need*100)+"%";
document.getElementById("txList").innerHTML=state.transactions.map(t=>`<div class="row"><span>${t.description}<small>${new Date(t.createdAt).toLocaleString("pt-BR")} · ${t.status}</small></span><b>${t.amount>0?"+":""}${t.amount} 🪙</b></div>`).join("")||'<p class="muted">Sem histórico.</p>';
document.getElementById("withdrawList").innerHTML=state.withdrawals.map(w=>`<div class="row"><span>${w.amount} 🪙 · ${w.method}<small>${new Date(w.createdAt).toLocaleString("pt-BR")}</small></span><b>${w.status}</b></div>`).join("")||'<p class="muted">Nenhuma solicitação.</p>';
document.getElementById("missionsList").innerHTML=state.missions.map(m=>{const done=p.completedMissions.includes(m.id);return `<div class="mission"><div class="mission-top"><div><b>${m.title}</b><p class="muted">${m.description}</p></div><span class="tag">+${m.reward} 🪙</span></div><button ${done?"disabled":""} onclick="claim('${m.id}')">${done?"✓ Resgatada":"Resgatar recompensa"}</button></div>`}).join("");
document.getElementById("rankList").innerHTML=state.leaderboard.map((x,i)=>`<div class="row"><span>#${i+1} 🥷 ${x.name}</span><b>Nv.${x.level} · ${x.coins} 🪙</b></div>`).join("");
}
async function startGame(){show("game");document.getElementById("levelLabel").textContent="FASE "+Math.min(10,state.player.completedLevels.length+1)}
async function collectReward(){try{state=(await api("/api/collect",{amount:25})).player;const s=await api("/api/state");state=s;render();flash("25 moedas virtuais coletadas!")}catch(e){flash(e.message)}}
async function completeLevel(){try{const level=Math.min(10,state.player.completedLevels.length+1);await api("/api/complete-level",{level});state=await api("/api/state");render();document.getElementById("levelLabel").textContent="FASE "+Math.min(10,state.player.completedLevels.length+1);flash("Fase concluída! Recompensa virtual adicionada.")}catch(e){flash(e.message)}}
function move(dir){const el=document.getElementById("player");let x=parseInt(getComputedStyle(el).left)||80;x=Math.max(10,Math.min(420,x+dir*35));el.style.left=x+"px"}
function jump(){const el=document.getElementById("player");el.style.transform="translateY(-100px)";setTimeout(()=>el.style.transform="",350)}
function attack(){const e=document.getElementById("enemy");e.style.transform="translateX(35px) rotate(15deg)";setTimeout(()=>e.style.transform="",220);flash("Ataque executado!")}
function dodge(){const el=document.getElementById("player");el.style.transform="translateX(70px) scale(.8)";setTimeout(()=>el.style.transform="",250)}
async function claim(id){try{await api("/api/claim-mission",{id});state=await api("/api/state");render();flash("Recompensa da missão adicionada.")}catch(e){flash(e.message)}}
async function daily(){try{const d=await api("/api/daily");state=await api("/api/state");render();flash(d.claimed?"Bônus diário resgatado!":"Bônus de hoje já foi resgatado.")}catch(e){flash(e.message)}}
function openModal(type){const c=document.getElementById("modalContent");if(type==="deposit")c.innerHTML=`<p class="eyebrow">DEMONSTRAÇÃO</p><h2>Adicionar moedas</h2><p class="notice">Esta tela não processa pagamento real. Ela registra uma simulação.</p><label>Valor demonstrativo</label><input id="amount" type="number" min="1" placeholder="Ex.: 50"><label>Método</label><select id="method"><option>Pix (simulação)</option><option>Cartão (simulação)</option></select><button class="primary" onclick="deposit()">CONFIRMAR SIMULAÇÃO</button>`;else c.innerHTML=`<p class="eyebrow">DEMONSTRAÇÃO</p><h2>Solicitar saque</h2><p class="notice">As moedas não têm valor monetário. Nenhum dinheiro real será enviado.</p><label>Moedas virtuais</label><input id="amount" type="number" min="1" max="${state.player.coins}" placeholder="Máx. ${state.player.coins}"><label>Chave/identificador</label><input id="method" placeholder="Ex.: chave-pix-demo"><button class="primary" onclick="withdraw()">SOLICITAR (SIMULAÇÃO)</button>`;document.getElementById("modal").classList.add("open")}
function closeModal(){document.getElementById("modal").classList.remove("open")}
async function deposit(){try{const amount=Number(document.getElementById("amount").value);const method=document.getElementById("method").value;const d=await api("/api/deposit-demo",{amount,method});closeModal();state=await api("/api/state");render();flash(d.notice)}catch(e){flash(e.message)}}
async function withdraw(){try{const amount=Number(document.getElementById("amount").value);const method=document.getElementById("method").value;const d=await api("/api/withdraw-demo",{amount,method});closeModal();state=await api("/api/state");render();flash(d.notice)}catch(e){flash(e.message)}}
function flash(msg){let x=document.getElementById("flash");if(!x){x=document.createElement("div");x.id="flash";x.style.cssText="position:fixed;left:50%;bottom:25px;transform:translateX(-50%);background:#171c28;border:1px solid #d8a73d;color:#fff;padding:13px 17px;border-radius:12px;z-index:99;max-width:90%;text-align:center";document.body.appendChild(x)}x.textContent=msg;x.style.display="block";clearTimeout(window.ft);window.ft=setTimeout(()=>x.style.display="none",3200)}
load();
